### ISSUE TITLE
CGSpace Test is running CG Core v2

### ISSUE THREAD

**Issue by alanorth** [AgriculturalSemantics/cg-core#11]
Just an update that [CGSpace's public test server](https://dspacetest.cgiar.org/) is now running CG Core v2 (with the few caveats that I've highlighted here on GitHub). We need to discuss among all of our partners and do some serious testing. We have dozens of institutions harvesting us via OAI, REST, and HTML scraping—for example, to CIAT, CCAFS, WLE, and ILRI Drupals, BMGF publications website, Land Portal, Altmetric, Google, etc—and we will have to notify them and give them timelines about when the changes will be applied to the CGSpace production server.

 I will keep you posted. It would be good to touch base with @marieALaporte again!

**Comment by marieALaporte** [comment]
@alanorth great news!
