### ISSUE TITLE
contributor type Lead project centre should be only Lead project entity?

### ISSUE THREAD

**Issue by marieALaporte** [AgriculturalSemantics/cg-core#12]
In order to make CG Core usable outside CGIAR, the contributor type "Project Lead Centre" can be made more generic by being just "Project Lead Entity"

**Comment by alanorth** [comment]
Looks good to me. :+1: Seems appropriate for the field name to be more generic. In the schema itself we can give a description that this indicates the center, institute, organization, etc that is leading the project.
