### ISSUE TITLE
Adjust casing of HasMetadata

### ISSUE THREAD

**Issue by alanorth** [AgriculturalSemantics/cg-core#6]
The casing of the term `HasMetadata` sticks out compared to other DC fields with multiple words, for example `accessRights`, `isPartOf`, `rightsHolder`, etc. Should we change that to `hasMetadata`?

**Comment by marieALaporte** [comment]
yes, I agree. It should be changed to `hasMetadata`
I will make the change when I do the other ones. I will ask you to review and merge the PR
