### ISSUE TITLE
Alternative title field?

### ISSUE THREAD

**Issue by alanorth** [AgriculturalSemantics/cg-core#9]
CGSpace supports an "alternative title" metadata element, which we are currently storing in the `dc.title.alternative` field¹. I notice that [DCTERMS](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/?v=terms) has a `dcterms.alternative` for exactly this purpose, but CG Core doesn't have it. Should we add it?

Thank you!

―
¹ There are only about 470 occurrences of this metadata (out of ~80,000 items on CGSpace), so it's not very popular, but nevertheless...

**Comment by marieALaporte** [comment]
I'm going to add it. As Dublin Core provides the exact match of what you need, it is easy. I'll close the issue when it is done.
Thanks
